[build]
  command = "pnpm run netlify"
  functions = "api/endpoints"
  publish = "./dist"

[dev]
  command = "pnpm run watch"

[context.production.environment]
  NODE_VERSION = '18.13.0'
  AWS_LAMBDA_JS_RUNTIME = 'nodejs18.x'

  [[redirects]]
    from ="/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[functions]
  node_bundler = "esbuild"
